export const PAYMENT = {
  PAYMENT_LATER: "PAYMENT_LATER",
  VN_PAYMENT: "VN_PAYMENT",
  PAYPAL: "PAYPAL",
};

export const enum TPAYMENT {
  PAYMENT_LATER = "PAYMENT_LATER",
  VN_PAYMENT = "VN_PAYMENT",
  PAYPAL = "PAYPAL",
}
